config/routes.rb
Rails.application.routes.draw do

#=================== HOME PAGE =========================#
  root "static_pages#home"
  #form search
  get '/search' => 'static_pages#search' , :as => 'search_car'
#=== UserLogin / sing_up /show_profil with avatars =====#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: [:index,:show] do
    resources :avatars , only: [:create]
  end
#===============  Add_new_car/Remove  ==================#
  resources :car  do
    resources :pictures , only: [:create]
    resources :likes
  end
#==============  Comment for cars  =====================#
  resources :comments
  resources :answers
#==  Link for private_messages (user <--> other_user) ==#
  resources :conversations do #contact list
    resources :messages #message content
  end
#=================  Abonnement  ========================#
resources :abonnement, only:[:index]
resources :premiums, only: [:create,:destroy]
resources :golds, only: [:create,:destroy]
#=======================================================#
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper

  def home
    @vente = Car.all.where(option:"Vente")
    @vente = @vente[0..5]
    @location = Car.all.where(option:"Location")
    @location = @location[0..5]

    @car = Car.all
    @car = @car[0..5]
    @mark = Mark.all
    @model = Model.all
    @type = Type.all
    @energy = Energy.all
    @city = City.all
  end

  def search
    if params[:search_model].blank?
      if params[:car] == nil
        redirect_back fallback_location: '/', allow_other_host: false
      else
        @car = params[:car]
        if (@car[:mark_id] != "")  || (@car[:model_id] != "") || (@car[:energy_id] != "") || (@car[:type_id] != "") || (@car[:city_id] != "") || (@car[:year] != "") || (@car[:transmission] != "") || (@car[:climatisation] != "") || (@car[:option] != "") || (@car[:price] != "0" && @car[:price] != "")
          @results = Car.all

          if @car[:mark_id] != ""
            @results = @results.where(mark_id:@car[:mark_id])
            if @results.length == 0
              return
            end
          end

          if @car[:model_id] != ""
            @results = @results.where(model_id:@car[:model_id])
            if @results.length == 0
              return
            end
          end

          if @car[:energy_id] != ""
              @results = @results.where(energy_id:@car[:energy_id])
              if @results.length == 0
                return
              end
          end

          if @car[:type_id] != ""
            @results = @results.where(type_id:@car[:type_id])
            if @results.length == 0
              return
            end
          end

          if @car[:city_id] != ""
            @results = @results.where(city_id:@car[:city_id])
            if @results.length == 0
              return
            end
          end

          if @car[:year] != ""
            @results = @results.where(year:@car[:year].to_i)
            if @results.length == 0
              return
            end
          end

          if @car[:transmission] != ""
            @results = @results.where(transmission:@car[:transmission])
            if @results.length == 0
              return
            end
          end

          if @car[:climatisation] != ""
            @results = @results.where(climatisation:@car[:climatisation])
            if @results.length == 0
              return
            end
          end

          if @car[:option] != ""
            @results = @results.where(option:@car[:option])
            if @results.length == 0
              return
            end
          end

          if @car[:price] != "0" && @car[:price] != ""
            @new_result = []
            @results.each do |car|
              if car.price <= @car[:price].to_i
                @new_result.push(car)
              end
            end
            @results = @new_result
            if @results.length == 0
              return
            end
          end

        else
          redirect_back fallback_location: '/', allow_other_host: false
        end
      end
    else
      @parameter = params[:search_model]
      @mark = Mark.all.where("name LIKE ?", "#{@parameter.downcase}%")
      @results = @mark[0].cars
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def car_option_vente(cars)
    array_cars = []
    cars.each do |car|
      if car.option == 'Vente'
        array_cars.push(car)
      end
    end
    return array_cars
  end
  def car_option_location(cars)
    array_cars = []
    cars.each do |car|
      if car.option == 'Location'
        array_cars.push(car)
      end
    end
    return array_cars
  end
end

app/views/static_pages/_search_bar_completed.html.erb
<div>
<%= form_for(@car, url: search_car_path, method: :get ) do |f| %>
  <div class="form-row">
    <div class="col">
      <%= f.label :mark_id, "Marque" %>
      <%= f.select :mark_id, options_for_select(@mark.collect{ |u| [u.name, u.id] }), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :model_id, "Modèle" %>
      <%= f.select :model_id, options_for_select(@model.collect{ |u| [u.name, u.id] }), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :energy_id, "Energie" %>
      <%= f.select :energy_id, options_for_select(@energy.collect{ |u| [u.name, u.id] }), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :type_id, "Type" %>
      <%= f.select :type_id, options_for_select(@type.collect{ |u| [u.name, u.id] }), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      <%= f.label :city_id, "Ville" %>
      <%= f.select :city_id, options_for_select(@city.collect{ |u| [u.name, u.id] }), { include_blank: true } , prompt: 'Choisissez une ville', class: "form-control" %>
    </div>
    <div class="col">
       <%= f.label :year, "Anneé" %>
       <%= f.select :year, (Time.zone.now.year - 119)..(Time.zone.now.year), { include_blank: true }, class:"form-control"%>
    </div>
    <div class="col">
      <%= f.label :transmission, "Transmission" %>
      <%= f.select :transmission,  options_for_select(["Automatique","Manuelle","Semi-automatique"]), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :climatisation, "Climatisation"%>
      <%= f.select :climatisation,  options_for_select(["Oui","Non"]), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      <%= f.label :option, "Option"%>
      <%= f.select :option,  options_for_select(["Vente","Location"]), {include_blank: true}, prompt: 'Choisissez une', class: "form-control" %>
    </div>
    <div class="col">
       <%= f.label :price, "Prix maximum" %>
       <%= f.number_field :price,value:0,min:0, class: "form-control"%>
    </div>
  </div>
  <div class="form-row chercher">
    <div class="col">
      <%= f.submit 'Recherche', class:"btn btn-warning btn-block"%>
    </div>
  </div>
<% end %>
</div>

app/views/static_pages/home.html.erb
<!--
    ==========================PAGE header ==========================
  -->
<header class="masthead bg-dark" id="top">
  <div class="container">
    <div class="intro-text head-pos">
      <div class="intro-lead-in text-coul">
        Bienvenue chez Madafullcar!
      </div>   
      <div class="intro-lead-in text-uppercase text-style">
          Des offres de vente et de location de voiture sur mesure
      </div>
      <a href="<%=car_index_path(annonce:'location')%>", class="btn btn-primary btn-xl text-uppercase js-scroll-trigger btn-render text-dark">voiture à louer</a>
      <a href="<%=car_index_path(annonce:'vente')%>" class="btn btn-primary btn-xl text-uppercase js-scroll-trigger btn-render text-dark" href="#">voitures à vendre</a>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger btn-render text-dark" href="/car/new">Ajouter une annonce</a>
    </div>
  </div>
</header>

  <!--
    ==========================PAGE DE Recherche==========================
  -->
<section class="page-section" id="services">
  <div class="container">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading text-uppercase">Chercher votre voiture ici </h2>
      <%= render 'search_bar_completed' %>
    </div>
  </div>
</section>
  
  <!--
    ==========================PAGE service ==========================
  -->
<section class="page-section" id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Services :</h2>
          <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="far fa-calendar-check" class="fa-stack-1x fa-inverse img"></i>
        </span>
        <h4 class="service-heading">Vente</h4>
        <p class="text-muted">Les véhicules sont  proposés par les particuliers et professionnelles. 
        Ils sont fournis avec les informations indispensables pour vous aider à faire votre choix.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="far fa-calendar-check" class="fa-stack-1x fa-inverse img"></i>
        </span>
        <h4 class="service-heading">Location</h4>
        <p class="text-muted">Les véhicules sont disponibles par des réservations en ligne ou 
        par contact avec leurs propriétaires. </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="far fa-calendar-check" class="fa-stack-1x fa-inverse img"></i>
        </span>
        <h4 class="service-heading">Messages</h4>
        <p class="text-muted">Nous offrons la possibilité de contacter par message les propriétaires directement dans le site.</p>
      </div>
    </div>
  </div>
</section>

<!--
    ==========================PAGE annonces abonnement ==========================
  -->
<header class="masthead">
  <div class="card md-3 header">
    <div class="row no-gutters">
      <div class="col-md-7  header-fond">
        <div class="card-body">
          <div id="abonnement">
            <div class="intro-lead-in bg-warning">
              <h3>Abonnements</h3>
            </div>
            <div class="intro-heading text-uppercase card-text">
              Bénéficier de nos offres d'Abonnements
            </div> <br>
            <div class="text-abot">
              <p>Nos offres d'abonnements sont divisés en deux catégeories bien précis: Premium et Gold.<br>
                <strong class="text-s">Premium</strong>: Destiné à des particuliers qui souhaitent avoir plus de visibilité pour leurs annonces.
                Cette offre comporte un affichage en page d'accueil est un meilleur placement dans
                les résultats des recherches. Poster des annonces de façon illimitée,et en  plus la possibilité de s'afficher dans la
                page Facebook de Madafullcar.<br>
                <strong class="text-s">Gold</strong>: Pour les professionnelles qui veulent se faire connaitre et se rapprocher de leurs vraies clientèles.
                Dans cette offre on propose en plus du contenu du pack premium; un domaine dédié dans la page d'acceuil, des visibilités améliorées dans les résultats
                des recherches. Affichage illimité dans notre page facebook.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <%= image_tag 'audi.jpg', class:"card-img header" %>
      </div>
    </div>
  </div>
</header>

  <!--
    ==========================PAGE de vente ==========================
  -->

<section id="work" class="portfolio-mf sect-pt4 route">
  <div class="container" id="gold">
    <div class="row">
      <div class="col-sm-12">
        <div class="title-box text-center">
          <h3 class="title-a">
          Vente
          </h3>
            <p class="subtitle-a">
              Les offres de vente.
            </p>
          <div class="line-mf">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <%@vente.each do |car| %>
        <div class="col-md-4">
          <div class="work-box">
            <div class="work-img img-w">
              <%if car.pictures.attached?%>
                <%= image_tag (car.pictures[0]), class:"img-fluid"%>
              <%else%>
                <%= image_tag (car.image_url), class:"img-fluid" %>
              <%end%>
            </div>
            <div class="work-content">
              <div class="row">
                <div class="col-sm-8">
                  <%if car.pictures.attached?%>
                    <span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span>
                  <%else%>
                    <span ><i class="fas fa-camera"> 1</i></span>
                  <%end%>
                    <h2 class="w-title"><%=car.mark.name%></h2>
                    <h2 class="w-title"><%=car.price%> Ar</h2>
                  <div class="w-more">
                    <span class="w-ctegory">A vendre</span> /ajouté le <span class="w-date"><%=car.created_at%></span>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="w-like">
                    <a href="car/<%=car.id%>" class="far fa-plus-square"></a>
                  </div>
                </div>
              </div>
            </div>
          <p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? '' : ''%></p>
        </div>
    </div>
      <%end%>
      <div class="plus">
        <strong><a href="<%=car_index_path(annonce:'vente')%>"> >> Voir plus </a></strong>
      </div>
    </div>
  </div>
</section>

<!--
    ==========================PAGE à propos et poster ==========================
  -->
<header class="masthead">
  <div class="card md-3 header">
    <div class="row no-gutters">
      <div class="col-md-7  header-fond">
        <div class="card-body">
          <div id="nous">
            <div class="intro-lead-in bg-warning">
							<h3>À propos de nous</h3>
						</div>
              <p class="card-text">Madafullcar est un site internet spécialisé dans la vente et location de voiture situé à Madagascar.
              Le site diffuse des annonces postées directement par des vendeurs particuliers et professionnels.
              Madafullcar vous permet de retrouver facilement les voitures en fonction de vos critères et exigences.</p>
          </div><br>
          <div>
              <div class="intro-lead-in bg-warning">
								<h3>Postez vos annonces </h3>
							</div>
                <p class="card-text">Créez facilement vos annonces sur Madafullcar en cliquant sur « poster ». La diffusion des annonces est à partir de 0 Ariary et sans engagement.
                Vous bénéficiez également d’un espace admin qui vous permet de suivre vos annonces et les appréciations de la communauté. </p>
                <p><a href="/car/new" class= "btn btn-primary text-body">Poster</a></p>
					</div>
				</div>
			</div>
			<div class="col-md-5">
				<%= image_tag 'suv.jpg', class:"card-img header"%>
			</div>
		</div>
	</div>
</header>

 <!--
    ==========================PAGE location ==========================
  -->
<section id="work" class="portfolio-mf sect-pt4 route">
 <div class="container" id="gold">
   <div class="row">
     <div class="col-sm-12">
       <div class="title-box text-center">
         <h3 class="title-a">
           Location
         </h3>
         <p class="subtitle-a">
           Nos offres de location.
         </p>
         <div class="line-mf"></div>
       </div>
     </div>
   </div>
   <div class="row">
   <%@location.each do |car| %>
     <div class="col-md-4">
       <div class="work-box">
       	<div class="work-img img-w">
        	<%if car.pictures.attached?%>
          	<%= image_tag (car.pictures[0]), class:"img-fluid"%>
          <%else%>
            <%= image_tag (car.image_url), class:"img-fluid" %>
          <%end%>
        </div>
        	<div class="work-content">
          	<div class="row">
            	<div class="col-sm-8">
              	<%if car.pictures.attached?%>
               		<span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span>
                <%else%>
                	<span ><i class="fas fa-camera"> 1</i></span>
                <%end%>
                	<h2 class="w-title"><%=car.mark.name%></h2>
                 	<h2 class="w-title"><%=car.price%> Ar/jour</h2>
                 <div class="w-more">
                   <span class="w-ctegory">A louer</span> /ajouté le <span class="w-date"><%=car.created_at%></span>
                 </div>
              </div>
              <div class="col-sm-4">
              	<div class="w-like">
                	<a href="car/<%=car.id%>" class="far fa-plus-square"></a>
                </div>
              </div>
            </div>
          </div>
           <p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? '' : ''%></p>
       </div>
    </div>
   <%end%>
      <div class="plus">
        <strong><a href="<%=car_index_path(annonce:'location')%>"> >> Voir plus </a></strong>
      </div>
	 </div>
	</div>
</section>

app/views/static_pages/search.html.erb
<br><br><br><br><br><br>
<!--LIST AUTO EN VENTE-->
<% if car_option_vente(@results).empty? && car_option_location(@results).empty? %>
  <h1>Aucun resultats pour ces informations</h1>
<% end %>

<% unless car_option_vente(@results).empty? %>
  <% cars = car_option_vente(@results) %>
   <section id="work" class="portfolio-mf sect-pt4 route">
      <div class="container" id="gold">
        <div class="row">
          <div class="col-sm-12">
            <div class="title-box text-center">
              <h3 class="title-a">
                Resultats de recherche pour les voitures en vente
              </h3>
              <p class="subtitle-a">
                Achetez votre voiture de rêve
              </p>
              <div class="line-mf"></div>
            </div>
          </div>
        </div>
        <div class="row">
        <% cars.each do |car| %>
          <div class="col-md-4">
            <div class="work-box">
                <div class="work-img img-w">
                  <%if car.pictures.attached?%>
                  <%= image_tag (car.pictures[0]), class:"img-fluid"%>
                <%else%>
                  <%= image_tag (car.image_url), class:"img-fluid" %>
                  <%end%>
                </div>
                <div class="work-content">
                  <div class="row">
                    <div class="col-sm-8">
                    <%if car.pictures.attached?%>
                    <span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span>
                     <%else%>
                     <span ><i class="fas fa-camera"> 1</i></span>
                     <%end%>
                      <h2 class="w-title"><%=car.mark.name%></h2>
                      <h2 class="w-title"><%=car.option%></h2>
                    </div>
                    <div class="col-sm-4">
                      <div class="w-like">
                        <a href="car/<%=car.id%>" class="fas fa-info-circle"></a>
                      </div>
                    </div>
                  </div>
                </div>
                <p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? 'Likes' : 'Like'%></p>

            </div>

          </div>
           <%end%>
          </div>
        </div>
      </section>

<% end %>




<!--LIST AUTO EN LOCATION-->

<% unless car_option_location(@results).empty? %>
  <% cars = car_option_location(@results) %>
   <section id="work" class="portfolio-mf sect-pt4 route">
      <div class="container" id="gold">
        <div class="row">
          <div class="col-sm-12">
            <div class="title-box text-center">
              <h3 class="title-a">
                Resultats de recherche pour les voitures en location
              </h3>
              <p class="subtitle-a">
                Louez votre voiture de rêve
              </p>
              <div class="line-mf"></div>
            </div>
          </div>
        </div>
        <div class="row">
        <% cars.each do |car| %>
          <div class="col-md-4">
            <div class="work-box">
                <div class="work-img img-w">
                  <%if car.pictures.attached?%>
                  <%= image_tag (car.pictures[0]), class:"img-fluid"%>
                <%else%>
                  <%= image_tag (car.image_url), class:"img-fluid" %>
                  <%end%>
                </div>
                <div class="work-content">
                  <div class="row">
                    <div class="col-sm-8">
                    <%if car.pictures.attached?%>
                    <span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span>
                     <%else%>
                     <span ><i class="fas fa-camera"> 1</i></span>
                     <%end%>
                      <h2 class="w-title"><%=car.mark.name%></h2>
                      <h2 class="w-title"><%=car.option%></h2>
                    </div>
                    <div class="col-sm-4">
                     <div class="w-like">
                        <a href="car/<%=car.id%>" class="fas fa-info-circle"></a>
                      </div>
                    </div>
                  </div>
                </div>
                 <p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? 'Likes' : 'Like'%></p>
            </div>
          </div>
           <%end%>
          </div>
        </div>
      </section>
<% end %>