config/routes.rb
Rails.application.routes.draw do

#=================== HOME PAGE =========================#
  root "static_pages#home"
  #form search
  get '/search' => 'static_pages#search' , :as => 'search_car'
#=== UserLogin / sing_up /show_profil with avatars =====#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: [:index,:show] do
    resources :avatars , only: [:create]
  end
#===============  Add_new_car/Remove  ==================#
  resources :car  do
    resources :pictures , only: [:create]
    resources :likes
  end
#==============  Comment for cars  =====================#
  resources :comments
  resources :answers
#==  Link for private_messages (user <--> other_user) ==#
  resources :conversations do #contact list
    resources :messages #message content
  end
#=================  Abonnement  ========================#
resources :abonnement, only:[:index]
resources :premiums, only: [:create,:destroy]
resources :golds, only: [:create,:destroy]
#=======================================================#
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	belongs_to :comment
end

app/models/car.rb
class Car < ApplicationRecord
  #car relation create
  belongs_to :mark
  belongs_to :model
  belongs_to :type
  belongs_to :energy
  belongs_to :city
  belongs_to :user
  #car relation for comments
  has_many :comments
  has_many :likes, dependent: :destroy
  #other relation
  has_many_attached :pictures
  #Validation
	validates :price, presence: true, numericality: {greater_than: 0}
	validates :description, presence: true, length: {maximum: 500}
	validates :etat, presence: true,length: {maximum: 40}
	validates :year, presence: true
  validates :mileage, presence: true, numericality: {greater_than: 0}
  validates :climatisation, presence: true, length: {maximum: 3}
  validates :transmission, presence: true, length: {maximum: 30}
  validates :telephone, presence: true, numericality: {minimum: 10, maximum: 15}
  validates :option, presence: true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :cars
	validates :name, presence: true,length: {maximum: 150}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :car
	belongs_to :user
	has_many :answers
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_many :messages, dependent: :destroy

end

app/models/energy.rb
class Energy < ApplicationRecord
	has_many :cars
	validates :name, presence: true,length: {maximum: 40}
end

app/models/gold.rb
class Gold < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/mark.rb
class Mark < ApplicationRecord
	has_many :cars
	has_many :models
	validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :content, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
  
end

app/models/model.rb
class Model < ApplicationRecord
	has_many :cars
	validates :name, presence: true
end

app/models/premium.rb
class Premium < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :cars
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  
  #relation on create
  devise :database_authenticatable, :registerable, :omniauthable, 
     :recoverable, :rememberable, :trackable, 
     :omniauth_providers => [:facebook, :google_oauth2]

  has_one_attached :avatar
  #relation for likes cars
  has_many :likes, dependent: :destroy
  #relation for comments
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy
  #relation for cars
  has_many :cars
  #relation for messages
  has_many :sent_conversations, foreign_key: 'sender_id', class_name: "Conversation", dependent: :destroy
  has_many :received_conversations, foreign_key: 'recipient_id', class_name: "Conversation", dependent: :destroy
  #relation of abonnement
  has_one :premium
  has_one :gold
  has_many :user_provider, :dependent => :destroy
  def welcome_send #message de bienvenu a chaque nouvelle utilisateur inscrit
    UserMailer.welcome_email(self).deliver_now
  end

end

app/models/user_provider.rb
class UserProvider < ApplicationRecord
	belongs_to :user
	def self.find_for_facebook_oauth(auth)

        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                			first_name: auth.info.first_name,
                    		last_name: auth.info.last_name,
                            email: auth.info.email,
                            password: Devise.friendly_token[0,20],
                            #password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                              user_id: user.id
                    )
                user
            end
        end
    end
    def self.find_for_google_oauth(auth)
        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                    first_name: auth.info.last_name,
                    last_name: auth.info.first_name,
                    email: auth.info.email,
                    password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                            user_id: user.id
                    )
                user
            end
        end
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = UserProvider.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication               
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = UserProvider.find_for_google_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  
  def failure
   	redirect_to "/users/sign_in"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:show]

  def index
    @users = User.all
    @user = []
    nom = params[:last_name].downcase
    @users.each do |user|
      if (user.last_name == nom) || (user.first_name == nom) || (user.first_name == nom.split[0]) || (user.last_name == nom.split[1]) 
        @user << user
      end
    end
  end


  def show
    @user = User.find(current_user.id)
    @ventecar=[]
    @listvente = @user.cars.where(option: "Vente")
    @listvente.each do |car|
      @ventecar << car
    end
    @locationcar=[]
    @listlocation=@user.cars.where(option: "Location")
    @listlocation.each do |car|
      @locationcar << car
    end

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/golds_helper.rb
module GoldsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h3>RESULTAT DE RECHERCHE pour "<%=params[:last_name]%>"</h3>
  <%@user.each do |user| %>
    <% if user.id != current_user.id%>
      <strong>
        <ol>
          <li>
          	<%if user.avatar.attached?%>
          		<%= image_tag (user.avatar), class:"left"%>
          	<%else%>
          		<img src="https://www.cbdloire.fr/wa_images/profil%20vide_1.png?v=1d0lgmf" alt="Avatar" class="left">
          	<%end%>
      	   <%= link_to "#{(user.first_name).titleize} #{(user.last_name).titleize} ", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>  <i class="far fa-comment-dots"></i><br>Email : <%="#{user.email}"%>
          </li>
        </ol>
      </strong>
    <%else%>
    <h5>Aucun resultat</h5>
    <%end%>
  <%end%>

app/views/users/show.html.erb
<div class="container">
  <div class="row my-2">
    <div class="col-lg-8 order-lg-2">
      <ul class="nav nav-tabs">
        <li class="nav-item">
					<a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
        </li>
        <li class="nav-item">
          <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Historiques de vos annonces</a>
        </li>
      </ul>

            <!-- Profil  de l'utilisateur -->
      <div class="tab-content py-4">
        <div class="tab-pane active" id="profile">
          <h5 class="mb-3">Votre espace personnel</h5>
            <div class="row">
              <div class="col-md-6">
                  <h6>A propos de vous :</h6>
                    <p>
                      Nom: <%=@user.first_name%><br>								
										  Prénom: <%=@user.last_name%><br>
										  Nombre d'annonce(s) effectué(e): <%=@user.cars.count%> Voiture(s)
                    </p>
              </div>
            </div>
        </div>

						<!-- historique des annonces de l'user -->
        <div class="tab-pane" id="messages">
					<div class="alert alert-info alert-dismissable">
						<a class="panel-close close" data-dismiss="alert">×</a> Vous trouverez ici la listes de vos annonces. En vous remercie d'utliser notre service
					</div>
                  <!-- listes des ventes -->
						<hr class= "badge-dark">
							<h6>Vos listes de ventes:</h6>  
							<%if @listvente.length !=nil %>							
							  <ol>
								  <%for i in  0..(@listvente.length - 1)%>
									<li>
										<a href="/car/<%=@ventecar[i].id%>"><%=@ventecar[i].mark.name%>  <%=@ventecar[i].model.name%></a>
                    <%= link_to "modifier", edit_car_path(@ventecar[i]), method: :get, class: "badge badge-pill badge-info"%>
										<br> <strong> Ar</strong> <%=@ventecar[i].price%> <br>
                    <span> Like obtenu: </span>  👍 <%= @ventecar[i].likes.count%>
                  </li>
								  <%end%>
							  </ol>
              <%end%>
                <%if @listvente.length == 0 %>	
								  <p>Vous n'avez pas encore fait d'annonce de vente</p>
							  <%end%>
							     <!-- listes des locations -->
							<hr class= "badge-dark">
							  <h6>Vos listes de locations :</h6>
							    <%if @listlocation.length != nil%>	
							      <ol>
								      <%for i in  0..(@listlocation.length - 1)%>
									    <li>                             
										    <a href="/car/<%=@locationcar[i].id%>"><%=@locationcar[i].mark.name%> <%=@locationcar[i].model.name%></a>
                        <%= link_to "modifier", edit_car_path(@locationcar[i]), method: :get,class: "badge badge-pill badge-info"%>										
										    <br><strong> Ar </strong> <%=@locationcar[i].price%> <br>
                        <span> Like obtenu : </span>  👍 <%= @locationcar[i].likes.count%>           
									    </li>
								      <%end%>
							      </ol>							
                  <%end%>
                    <%if @listlocation.length == 0%>	                 
							        <p>Vous n'avez pas encore fait d'annonce de location</p>
							      <%end%>
							    <hr class= "badge-dark">
          </div>
      </div>
    </div>
            <%# Ajout d'avatar %>
        <div class="col-lg-4 order-lg-1 text-center">
          <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar,class:"card-img", alt: 'avatar' %>
        <%else%>
            <img src="//placehold.it/150" class="mx-auto img-fluid img-circle d-block" alt="avatar">
        <%end%>
            <h6 class="mt-2">Ajouter/Modifier la photo de profil</h6>
            <p> 
            <%= form_tag user_avatars_path(@user), multipart: true do %>
            <%= file_field_tag :avatar,accept: 'image/png,image/gif,image/jpeg' %> 
            <%= submit_tag "mettre à jour"%>
            <% end %>
            </p>
        </div>
    </div>
</div>


<div >
    <a href="/users/edit" class="btn btn-outline-info edit1">Editer votre profil</a>
</div>