config/routes.rb
Rails.application.routes.draw do

#=================== HOME PAGE =========================#
  root "static_pages#home"
  #form search
  get '/search' => 'static_pages#search' , :as => 'search_car'
#=== UserLogin / sing_up /show_profil with avatars =====#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: [:index,:show] do
    resources :avatars , only: [:create]
  end
#===============  Add_new_car/Remove  ==================#
  resources :car  do
    resources :pictures , only: [:create]
    resources :likes
  end
#==============  Comment for cars  =====================#
  resources :comments
  resources :answers
#==  Link for private_messages (user <--> other_user) ==#
  resources :conversations do #contact list
    resources :messages #message content
  end
#=================  Abonnement  ========================#
resources :abonnement, only:[:index]
resources :premiums, only: [:create,:destroy]
resources :golds, only: [:create,:destroy]
#=======================================================#
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	belongs_to :comment
end

app/models/car.rb
class Car < ApplicationRecord
  #car relation create
  belongs_to :mark
  belongs_to :model
  belongs_to :type
  belongs_to :energy
  belongs_to :city
  belongs_to :user
  #car relation for comments
  has_many :comments
  has_many :likes, dependent: :destroy
  #other relation
  has_many_attached :pictures
  #Validation
	validates :price, presence: true, numericality: {greater_than: 0}
	validates :description, presence: true, length: {maximum: 500}
	validates :etat, presence: true,length: {maximum: 40}
	validates :year, presence: true
  validates :mileage, presence: true, numericality: {greater_than: 0}
  validates :climatisation, presence: true, length: {maximum: 3}
  validates :transmission, presence: true, length: {maximum: 30}
  validates :telephone, presence: true, numericality: {minimum: 10, maximum: 15}
  validates :option, presence: true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :cars
	validates :name, presence: true,length: {maximum: 150}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :car
	belongs_to :user
	has_many :answers
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_many :messages, dependent: :destroy

end

app/models/energy.rb
class Energy < ApplicationRecord
	has_many :cars
	validates :name, presence: true,length: {maximum: 40}
end

app/models/gold.rb
class Gold < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/mark.rb
class Mark < ApplicationRecord
	has_many :cars
	has_many :models
	validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :content, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
  
end

app/models/model.rb
class Model < ApplicationRecord
	has_many :cars
	validates :name, presence: true
end

app/models/premium.rb
class Premium < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :cars
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  
  #relation on create
  devise :database_authenticatable, :registerable, :omniauthable, 
     :recoverable, :rememberable, :trackable, 
     :omniauth_providers => [:facebook, :google_oauth2]

  has_one_attached :avatar
  #relation for likes cars
  has_many :likes, dependent: :destroy
  #relation for comments
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy
  #relation for cars
  has_many :cars
  #relation for messages
  has_many :sent_conversations, foreign_key: 'sender_id', class_name: "Conversation", dependent: :destroy
  has_many :received_conversations, foreign_key: 'recipient_id', class_name: "Conversation", dependent: :destroy
  #relation of abonnement
  has_one :premium
  has_one :gold
  has_many :user_provider, :dependent => :destroy
  def welcome_send #message de bienvenu a chaque nouvelle utilisateur inscrit
    UserMailer.welcome_email(self).deliver_now
  end

end

app/models/user_provider.rb
class UserProvider < ApplicationRecord
	belongs_to :user
	def self.find_for_facebook_oauth(auth)

        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                			first_name: auth.info.first_name,
                    		last_name: auth.info.last_name,
                            email: auth.info.email,
                            password: Devise.friendly_token[0,20],
                            #password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                              user_id: user.id
                    )
                user
            end
        end
    end
    def self.find_for_google_oauth(auth)
        user = UserProvider.where(:provider => auth.provider, :uid => auth.uid).first
        unless user.nil?
            user.user
        else
            registered_user = User.where(:email => auth.info.email).first
            unless registered_user.nil?
                        UserProvider.create!(
                              provider: auth.provider,
                              uid: auth.uid,
                              user_id: registered_user.id
                              )
                registered_user
            else
                user = User.create!(
                    first_name: auth.info.last_name,
                    last_name: auth.info.first_name,
                    email: auth.info.email,
                    password: Devise.friendly_token[0,20],
                            )
                user_provider = UserProvider.create!(
                    provider:auth.provider,
                            uid:auth.uid,
                            user_id: user.id
                    )
                user
            end
        end
    end

end

app/controllers/abonnement_controller.rb
class AbonnementController < ApplicationController
  def index
  	@gold = User.find(current_user.id).gold
	@premium = User.find(current_user.id).premium
  end
end

app/helpers/abonnement_helper.rb
module AbonnementHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/golds_helper.rb
module GoldsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abonnement/index.html.erb
<h2 class="text-abonnement">Espace abonnement</h2>
  <div class="form abonner">
    <!-- abonnement gold -->
    <% if @gold != nil %>
      <div class="col-sm-4 space">
        <div class="card">
          <%=image_tag("car11.jpg",class:"card-img-top", alt: "Example Image")%>
            <div class="card-body color">
              <h4 class="text-center">Pack Gold</h4>
                <p class="card-text">Vous beneficiez de notre abonnement Gold. Si vous souhaitez se désabonner cliqué sur :</p>
              		<a href="/golds/<%=@gold.id%>" data-method="delete" class="btn btn-danger">Se désaboner</a>
            </div>
        </div>
      </div>         
    <% else %>
      <div class="container">
        <div class="row">
          <div class="col-sm-4 space">
            <div class="card">
              <%=image_tag("car12.jpg",class:"card-img-top", alt: "Voiture")%>
                <div class="card-body color">
                  <h4 class="text-center" >Pack Gold</h4>
                    <p class="card-text">Notre meilleur offre destiné aux entreprises et aux professionnelles.</p><br>
                      <%= form_tag golds_path do %>
                        <article>
                          <% if flash[:error].present? %>
                            <div id="error_explanation">
                              <p><%= flash[:error] %></p>
                            </div>
                          <% end %>
                            <label class="amount">
                              <p>100.000 Ar</p>
                            </label>
                        </article>
                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                              data-description="Un mois d'abonnement"
                              data-amount="9900000 ariary"
                              data-locale="auto"></script>
                      <% end %>
                </div>
            </div>
          </div>
    <!--abonnement premium  -->
						<% if @premium != nil %>
							<div class="col-sm-4 space">
								<div class="card">
									<%=image_tag("car15.jpg",class:"card-img-top", alt: "Example Image")%>
										<div class="card-body color">
											<h4 class="text-center">Pack Premium</h4>
												<p class="card-text">Vous utilisez notre abonnement Premium.Pour se retirer de cette offre veuillez cliquer sur :</p><br>
												 <a href="/premiums/<%=@premium.id%>" data-method="delete" class="btn btn-danger">Se désaboner</a>
										</div>
								</div>
							</div>
						<% else %>
							<div class="col-sm-4 space">
								<div class="card">
									<%=image_tag("car14.jpg",class:"card-img-top", alt: "Voiture")%>
										<div class="card-body color">
											<h4 class="text-center">Pack Prémium</h4>
												<p class="card-text">Notre offre à destination des particuliers, pour beneficier de plus de visibliter. </p>
													<%= form_tag premiums_path do %>
														<article>
															<% if flash[:error].present? %>
																<div id="error_explanation">
																	<p><%= flash[:error] %></p>
																</div>
															<% end %>
																<label class="amount">
																	<p>50000 Ar</p>
																</label>
														</article>
															<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
																			data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
																			data-description="Un mois d'abonnement"
																			data-amount="5000000 ariary"
																			data-locale="auto"></script>
															<% end %>
										</div>
								</div>
							</div>
						<% end %>
  			</div>        
			</div>
  	<% end %>
	</div>