config/routes.rb
Rails.application.routes.draw do

#=================== HOME PAGE =========================#
  root "static_pages#home"
  #form search
  get '/search' => 'static_pages#search' , :as => 'search_car'
#=== UserLogin / sing_up /show_profil with avatars =====#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :users, only: [:index,:show] do
    resources :avatars , only: [:create]
  end
#===============  Add_new_car/Remove  ==================#
  resources :car  do
    resources :pictures , only: [:create]
    resources :likes
  end
#==============  Comment for cars  =====================#
  resources :comments
  resources :answers
#==  Link for private_messages (user <--> other_user) ==#
  resources :conversations do #contact list
    resources :messages #message content
  end
#=================  Abonnement  ========================#
resources :abonnement, only:[:index]
resources :premiums, only: [:create,:destroy]
resources :golds, only: [:create,:destroy]
#=======================================================#
end

app/models/car.rb
class Car < ApplicationRecord
  #car relation create
  belongs_to :mark
  belongs_to :model
  belongs_to :type
  belongs_to :energy
  belongs_to :city
  belongs_to :user
  #car relation for comments
  has_many :comments
  has_many :likes, dependent: :destroy
  #other relation
  has_many_attached :pictures
  #Validation
	validates :price, presence: true, numericality: {greater_than: 0}
	validates :description, presence: true, length: {maximum: 500}
	validates :etat, presence: true,length: {maximum: 40}
	validates :year, presence: true
  validates :mileage, presence: true, numericality: {greater_than: 0}
  validates :climatisation, presence: true, length: {maximum: 3}
  validates :transmission, presence: true, length: {maximum: 30}
  validates :telephone, presence: true, numericality: {minimum: 10, maximum: 15}
  validates :option, presence: true
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  before_action :authenticate_user!, only:[:new,:create,:edit]

  def index
    if params[:annonce] != 'vente' && params[:annonce] != 'location'
      redirect_to '/'
    else
      if params[:annonce] == 'vente'
        @car = Car.where(option:'Vente')
      else
        @car = Car.where(option:'Location')
      end
    end
  end

  def show
    @car = Car.find(params[:id])
    @mark = Mark.find_by(name: "#{@car.mark.name}")
    @like = Like.new
    @like = @car.likes
     @cars = @mark.cars
    if user_signed_in?
      @pre_like = @car.likes.find { |like| like.user_id == current_user.id}
    end
    @comments = @car.comments
  end

  def new
    @car = Car.new
    @mark = Mark.all
    @model = Model.all
    @type = Type.all
    @energy = Energy.all
    @city = City.all
  end

  def create
    car_params = params.require(:car).permit(
      :price,
      :description,
      :etat,
      :year,
      :mileage,
      :number_place,
      :climatisation,
      :transmission,
      :telephone,
      :option,
      :status,
      :mark_id,
      :model_id,
      :type_id,
      :energy_id,
      :city_id,
      pictures: [])

    @car = Car.new(car_params)
    @car.user_id = current_user.id
    @car.save
    redirect_to(root_path)
  end

  def edit
    @car = Car.find(params[:id])
    @mark = Mark.all
    @model = Model.all
    @type = Type.all
    @energy = Energy.all
    @city = City.all
  end

  def update
    @car = Car.find(params[:id])
    car_params = params.require(:car).permit(
      :price,
      :description,
      :etat,
      :year,
      :mileage,
      :number_place,
      :climatisation,
      :transmission,
      :telephone,
      :option,
      :status,
      :mark_id,
      :model_id,
      :type_id,
      :energy_id,
      :city_id,
      pictures: [])
    @car.update(car_params)
    redirect_to(car_path(params[:id]))
  end
  def destroy
  end
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/car/_buy_car.html.erb
<section id="work" class="portfolio-mf sect-pt4 route">
	<div class="container" id="gold">
		<div class="row">
			<div class="col-sm-12">
				<div class="title-box text-center">
					<h3 class="title-a">
						Voiture en vente
					</h3>
						<p class="subtitle-a">
							Achetez votre voiture de rêve
						</p>
					<div class="line-mf">
					</div>
				</div>
			</div>
		</div>
		<div class="row">
      <!-- listes des voitures à vendre -->
			<%@car.each do |car| %>
			<div class="col-md-4">
				<div class="work-box">
					<div class="work-img img-w">
						<%if car.pictures.attached?%>
							<%= image_tag (car.pictures[0]), class:"img-fluid"%>
						<%else%>
							<%= image_tag (car.image_url), class:"img-fluid" %>
						<%end%>
					</div>
					<div class="work-content">
						<div class="row">
							<div class="col-sm-8">
								<%if car.pictures.attached?%>
									<span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span> 
								<%else%>  
									<span ><i class="fas fa-camera"> 1</i></span> 
								<%end%>
									<h2 class="w-title"><%=car.mark.name%></h2>
									<h2 class="w-title"><%=car.option%></h2>
									<h2 class="w-title"><%=car.price%> Ar</h2>
							</div>
							<div class="col-sm-4">
								<div class="w-like">
									<a href="car/<%=car.id%>" class="far fa-plus-square"></a>
								</div>
							</div>
						</div>
					</div>
						<p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? 'Likes' : 'Like'%></p>
				</div>
			</div>
			<%end%>
		</div>
	</div>
</section>

app/views/car/_shell_car.html.erb
<section id="work" class="portfolio-mf sect-pt4 route">
  <div class="container" id="gold">
    <div class="row">
      <div class="col-sm-12">
        <div class="title-box text-center">
          <h3 class="title-a">
              Voiture en Location
          </h3>
            <p class="subtitle-a">
              Louez votre voiture de rêve
            </p>
            <div class="line-mf"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <%@car.each do |car| %>
        <div class="col-md-4">
          <div class="work-box">
            <div class="work-img img-w">
              <%if car.pictures.attached?%>
                <%= image_tag (car.pictures[0]), class:"img-fluid"%>
              <%else%>
                <%= image_tag (car.image_url), class:"img-fluid" %>
              <%end%>
            </div>
              <div class="work-content">
                <div class="row">
                  <div class="col-sm-8">
                    <%if car.pictures.attached?%>
                      <span ><i class="fas fa-camera"> <%=car.pictures.length%></i></span>
                    <%else%>
                      <span ><i class="fas fa-camera"> 1</i></span>
                    <%end%>
                      <h2 class="w-title"><%=car.mark.name%></h2>
                      <h2 class="w-title"><%=car.option%></h2>
                      <h2 class="w-title"><%=car.price%> Ar∕jour</h2>
                  </div>
                  <div class="col-sm-4">
                    <div class="w-like">
                      <a href="car/<%=car.id%>" class="far fa-plus-square"></a>
                    </div>
                  </div>
                </div>
              </div>
                <p>(<%= car.likes.count %>) <i class="far fa-thumbs-up"></i> <%= (car.likes.count) > 1 ? 'Likes' : 'Like'%></p>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/car/create.html.erb
<h1>Car#create</h1>
<p>Find me in app/views/car/create.html.erb</p>

app/views/car/edit.html.erb
<div class="new-car">
  <div class="container">
    <h3 class="bg-warning text-new-car"> Page de modification d'une annonce</h3>
      <%=form_for @car,url:{action:"update"},html:{class:"form-horizontal"} do |f|%>
        <div class="form-row">
          <div class="col">
            <%= f.label :mark_id, "Marque" %>
              <%= f.select :mark_id, options_for_select(@mark.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :model_id, "Modèle" %>
              <%= f.select :model_id, options_for_select(@model.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :energy_id, "Energie" %>
              <%= f.select :energy_id, options_for_select(@energy.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :type_id, "Type" %>
              <%= f.select :type_id, options_for_select(@type.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :etat, "Etat" %>
            <%= f.select :etat,  options_for_select(["Impéccable","Bon état","Etat moyen","Mauvaise état"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :transmission, "Transmission" %>
            <%= f.select :transmission,  options_for_select(["Automatique","Manuelle","Semi-automatique"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :climatisation, "Climatisation"%>
            <%= f.select :climatisation,  options_for_select(["Oui","Non"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :option, "Option"%>
            <%= f.select :option,  options_for_select(["Vente","Location"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :city_id, "Ville" %>
            <%= f.select :city_id, options_for_select(@city.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une ville', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :year, "Anneé de sortie" %>
            <%= f.select :year, (Time.zone.now.year - 119)..(Time.zone.now.year),{},class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :mileage, "Kilometrage" %>
            <%=f.text_field :mileage,placeholder: "Kilometrage",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :number_place, "Nombre de place" %>
            <%=f.number_field :number_place,min:2,max: 64,placeholder: "Nombre de place",class: "form-control"%>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :telephone, "Telephone" %>
            <%=f.number_field :telephone,placeholder: "Telephone",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :price, "Prix" %>
            <%=f.number_field :price,placeholder: "Prix",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :pictures, "Ajoutez vos photos " %> <strong style="color:red;">*</strong>
            <%= f.file_field :pictures, placeholder: "Photo",accept: 'image/png,image/jpeg,image/jpg',multiple: true%>
          </div>
        </div>
        <div class="form-row">
          <%= f.label :description, "Description" %>
          <%=f.text_area :description,placeholder: "Description",class: "form-control"%>
        </div>
          <br>
        <div class="form-row">
          <%= f.submit 'Modifier', class:"btn btn-warning btn-block"%>
        </div>
      <%end%>
    <p> <strong style="color:red;">*</strong> Les photos chargées remplacent les derniers fichiers de votre annonce</p>
  </div>
</div>

app/views/car/index.html.erb
<% if @car.first.option == 'Vente' %>
	<%= render "buy_car.html.erb"%>
<% else %>
	<%= render "shell_car.html.erb"%>
<% end %>

app/views/car/new.html.erb
<div class="new-car">
  <div class="container">
    <h3 class="bg-warning text-new-car"> Page de création d'une annonce</h3>
      <%=form_for @car,url:{action:"create"},html:{class:"form-horizontal"} do |f|%>
        <div class="form-row">
          <div class="col">
            <%= f.label :mark_id, "Marque" %>
            <%= f.select :mark_id, options_for_select(@mark.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :model_id, "Modèle" %>
            <%= f.select :model_id, options_for_select(@model.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :energy_id, "Energie" %>
            <%= f.select :energy_id, options_for_select(@energy.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :type_id, "Type" %>
            <%= f.select :type_id, options_for_select(@type.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :etat, "Etat" %>
            <%= f.select :etat,  options_for_select(["Impéccable","Bon état","Etat moyen","Mauvaise état"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :transmission, "Transmission" %>
            <%= f.select :transmission,  options_for_select(["Automatique","Manuelle","Semi-automatique"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :climatisation, "Climatisation"%>
            <%= f.select :climatisation,  options_for_select(["Oui","Non"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :option, "Option"%>
            <%= f.select :option,  options_for_select(["Vente","Location"]), {}, prompt: 'Choisissez une', class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :city_id, "Ville" %>
            <%= f.select :city_id, options_for_select(@city.collect{ |u| [u.name, u.id] }), {}, prompt: 'Choisissez une ville', class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :year, "Anneé de sortie" %>
            <%= f.select :year, (Time.zone.now.year - 119)..(Time.zone.now.year),{},class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :mileage, "Kilometrage" %>
            <%=f.text_field :mileage,placeholder: "Kilometrage",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :number_place, "Nombre de place" %>
            <%=f.number_field :number_place,min:2,max: 64,placeholder: "Nombre de place",class: "form-control"%>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <%= f.label :telephone, "Telephone" %>
            <%=f.number_field :telephone,placeholder: "Telephone",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :price, "Prix" %>
            <%=f.number_field :price,placeholder: "Prix",class: "form-control"%>
          </div>
          <div class="col">
            <%= f.label :pictures, "Ajoutez vos photos " %> <strong style="color:red;">*</strong>
            <%= f.file_field :pictures, placeholder: "Photo",multiple: true,accept: 'image/png,image/gif,image/jpeg',required: true%>
          </div>
        </div>
        <div class="form-row">
          <%= f.label :description, "Description" %>
          <%=f.text_area :description,placeholder: "Description",class: "form-control"%>
        </div>
            <br>
        <div class="form-row">
          <%= f.submit 'create', class:"btn btn-warning btn-block"%>
        </div>
      <%end%>
    <p> <strong style="color:red;">*</strong> charger 5 photos, le premier photo s'affichera sur votre annonce.</p>
  </div>
</div>

app/views/car/show.html.erb
<div class="conteneur">
  <div class="content-car" id="left">
   <!--  Affichage en carousel des photos de la voiture  -->
    <div id="carouselExampleFade" class="carousel slide carousel-fade " data-ride="carousel">
      <div class="carousel-inner carousel-display">
        <div class="carousel-item active">
          <%if @car.pictures.attached?%>
            <%= image_tag (@car.pictures[0]), class:"img-display carousel-display",alt: '#{@car.model.name} #{@car.model.name}' %>
          <%else%>
            <%= image_tag (@car.image_url),class:"img-display carousel-display",alt: '#{@car.model.name} #{@car.model.name}' %>
          <%end%>
        </div>
        <% for i in 1..(@car.pictures.length-1)%>
        <div class="carousel-item">
          <%if @car.pictures.attached?%>
            <%= image_tag (@car.pictures[i]), class:"img-display carousel-display",alt: '#{@car.model.name} #{@car.model.name}' %>
          <%else%>
            <%= image_tag (@car.image_url),class:"img-display carousel-display",alt: '#{@car.model.name} #{@car.model.name}' %>
          <%end%>
        </div>
        <%end%>
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </div>
  <!-- Description de la voiture  -->  
      <div class="card-body back-color">
        <h5>A propos de la voiture:</h5>
          <ul class="about-car">
            <li><strong><i class="fas fa-car"></i> Marque : </strong><%=@car.mark.name%></li>
            <li><strong><i class="fab fa-medium-m"></i> Model: </strong><%=@car.model.name%></li>
            <li><strong><i class="far fa-calendar-check"></i>  Année: </strong><%=@car.year%> </li>
            <li><strong><i class="fas fa-angle-double-right"></i> Voiture en: </strong><%=@car.option%></li>
            <li><strong><i class="fas fa-snowflake"></i> Climatisation: </strong><%=@car.climatisation%></li>
            <li><strong><i class="fas fa-users"></i> Nombre de place: </strong><%=@car.number_place%></li>
            <li><strong><i class="fas fa-thermometer-quarter"></i> Etat: </strong><%=@car.etat%></li>
            <li><strong><i class="fas fa-signal"></i> Status : </strong><%=@car.status%></li>
              <%if @car.option == "Vente"%>
            <li><strong><i class="fas fa-euro-sign"></i> Prix: </strong><%=@car.price%> Ar</li>
              <% else %>
            <li><strong><i class="fas fa-euro-sign"></i> Prix: </strong><%=@car.price%> Ar/jours</li>
              <% end %>
            <li><strong><i class="fas fa-road"></i> Kilometrage: </strong><%=@car.mileage%> Km</li>
            <li><strong><i class="fas fa-sliders-h"></i> Transmission: </strong><%=@car.transmission%></li>
            <li><strong><i class="fas fa-hand-point-right"></i> Type: </strong><%=@car.type.name%></li>
            <li><strong><i class="fas fa-gas-pump"></i> Energie: </strong><%=@car.energy.name%></li>
            <li><strong><i class="fas fa-building"></i> Ville : </strong><%=@car.city.name%></li>
            <li><strong><i class="fas fa-phone-alt"></i> Contact : </strong><%=@car.telephone%></li>
            <li id="description"><strong>Description : </strong><%=@car.description%></li>
          </ul>
            <div id="likers">
              <% if @pre_like %>
                <p><%= @car.likes.count%> <%= link_to '', car_like_path(@car, @pre_like), method: :delete, class:'far fa-thumbs-down', remote: true%></p>
              <% else %>
                <p><%= @car.likes.count %> <%= link_to '', car_likes_path(@car), method: :post, class:'far fa-thumbs-up', remote: true%></p>
              <% end %>
            </div>
            <!-- boutton pour contacter -->
            <button type="button" class="btn btn-outline-warning">
              <% if user_signed_in? %>
                <%= link_to "Envoyer un message", conversations_path(sender_id: current_user.id, recipient_id: @car.user_id), method: 'post'%>
              <% else %>
                <%= link_to "Envoyer un message",new_user_session_path, method: 'post'%>
              <% end %>
            </button>
      </div>
  	</div>
	</div>
          <!--  fin => Description de la voiture  -->
  <div class="content-car" id="rigth">
      <div class="similaire sticky-top bg-dark">
          <h4> Voiture similaire </h4>
      </div>
        <%if @cars.length == 1%>

        <div  class="aucun">
           <p>Pas encore de voiture similaire</p>
        </div>

        <%end%>
      <%if @cars.length != nil%>
        <%@cars.each do |car|%>
            <% if @car.id != car.id %>
              <div class="card mb-3 card-w">
                <div class="row no-gutters">
                  <div class="col-md-5">
                      <%if car.pictures.attached?%>
                        <%= image_tag (car.pictures[0]), class:"card-img", alt:"#{car.mark.name}"%>
                      <%else%>
                        <%= image_tag (car.image_url), class:"card-img", alt:"#{car.mark.name}" %>
                      <%end%>
                  </div>
                  <div class="col-md-7">
                    <div class="card-body">
                    <a href="/car/<%=car.id%>">
                      <strong ><%=car.mark.name%></strong><br>
                      <%if @car.option == "Vente"%>
                      <strong >Ar <%=car.price%></strong> </a><br>
                      <%else%>
                      <strong >Ar <%=car.price%>/jour</strong> </a><br>
                      <%end%>
                      <span class="w-ctegory">En <%=car.option%></span> / <span class="w-date"> Ajouté le: <%=car.created_at%></span>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
        <%end%>
      <%end%>
  </div>
</div>

  <div class="comment-container">
    <%= render "/comments/comment.html.erb"%>
  </div>

app/views/car/updatedestroy.html.erb
<h1>Car#updatedestroy</h1>
<p>Find me in app/views/car/updatedestroy.html.erb</p>